language: php

sudo: required
dist: trusty

env:
  global:
    - MYSQL_USER=helpmeabstract
    - MYSQL_PASSWORD=securelol
matrix:
  fast_finish: true
  include:
    - php: 7

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin
  - composer self-update
  - composer validate

install:
  - composer install

script:
#  - vendor/bin/doctrine orm:info
  - vendor/bin/phpunit --configuration test/Unit/phpunit.xml --coverage-clover build/logs/clover.xml;
  - vendor/bin/php-cs-fixer fix --config=.php_cs --verbose --diff --dry-run;

notifications:
  email:
    on_success: change
    on_failure: change
  slack:
    secure: Dce/DARAkK3rdCzu01U9IxLx1PoWPYyGXmFj9jFDEbGHY955DZhFUXpHC5SSdpONpAZXayHcSPFCd3zBTS9IvppbQU+5vDseErK2hmw9yKlSGVRI7lcS0ytryNHtUwSLZdxGGaURRWo9zJblFeIAOZiKFebN5VRpYTMA/J0flOA=

after_success:
  - make deploy-staging AWS_PROFILE=default AWS_REGION=us-east-1