version: '2'
services:
  app:
    build: .
    environment:
      - MYSQL_USER=helpmeabstract
      - MYSQL_PASSWORD=securelol
      - ENV=development
    volumes:
      - .:/var/www
    ports:
      - "8080:80"
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=helpmeabstract
      - MYSQL_USER=helpmeabstract
      - MYSQL_PASSWORD=securelol
      - MYSQL_RANDOM_ROOT_PASSWORD=true
